### ISSUE TITLE
Best value for buffer size?

### ISSUE THREAD

**Issue by AndroidDesigner** [techpotatoes/pitch_detector_dart#4]
Hello everyone.
I want to use this package but I don't know what is best value for the ``buffer size``?

**Comment by techpotatoes** [comment]
Hey, I just refresh the sample app and release new versions of the libraries. Everything should be up-to-date. Have a look at -> https://github.com/techpotatoes/pitchup_flutter_sample

**Comment by techpotatoes** [comment]
Hey, I just refresh the sample app and release new versions of the libraries. Everything should be up-to-date. Have a look at -> https://github.com/techpotatoes/pitchup_flutter_sample
