### ISSUE TITLE
Weird values

### ISSUE THREAD

**Issue by Roee-Tsur** [techpotatoes/pitch_detector_dart#6]
Hey,

I seem to always be getting pitch values between 23000-24000 no matter how I change my voice, does that make sense?

Awesome library, thanks!

**Comment by techpotatoes** [comment]
Hey there,

Have you tested using the sample app? 

Cheers

**Comment by Roee-Tsur** [comment]
Thanks for the quick reply!
I tested this with my own implementation, but same record library with the pcm16bits encoder type.

**Comment by techpotatoes** [comment]
Have you tried using the same buffer size, sample rate and bitRate as I'm using in the example? Just so you can rule all these things out.

**Comment by Roee-Tsur** [comment]
The only difference is that I used sample rate of 2, when i tried using same as you, 1. i got results around -23,000.

I can try running you app as a whole and see if the issue is 100% in my implementation. I'll let you know when I have results.
